### ISSUE TITLE
Тест на MODX 3

### ISSUE THREAD

**Issue by EMDM45** [Element1493/modx_scssphp#1]
Тестируя MODX 3 (на локальном компьютере под Windows 7), установил компонент SCSS из modstore.
Столкнулся со следующими проблемами.
1. Настройка **scss.importPaths** обязательна, даже если файлы импорта находятся в одной папке с файлом из **scss.fileScss**. Потому что если оставить её пустой, тогда в журнале вылезает ошибка о том, что не получилось найти файл.
2. Если удалить скомпилированный CSS файл, а потом снова запустить сниппет, то новый файл НЕ будет создан. Он создастся только после любого изменения в SCSS.
3. После компиляции у меня вот такое получилось в CSS (переменные не "распарсились"):
```css
:root{--font-family: $font-family;--ui-font-family: $ui-font-family}
```
4. Ошибка в журнале при компиляции (насколько понял только при первом создании CSS):
```
...30.include.cache.php : 95) PHP warning: mkdir(): File exists
...30.include.cache.php : 95) SCSS - Не удалось создать директорию: Z:/home/modx.local/3//assets/styles
```

**Comment by Element1493** [comment]
Спасибо, что указали на мои ошибки.
Как будет время исправлю.

**Comment by Element1493** [comment]
> Тестируя MODX 3 (на локальном компьютере под Windows 7), установил компонент SCSS из modstore. Столкнулся со следующими проблемами.
> 
> 1. Настройка **scss.importPaths** обязательна, даже если файлы импорта находятся в одной папке с файлом из **scss.fileScss**. Потому что если оставить её пустой, тогда в журнале вылезает ошибка о том, что не получилось найти файл.
> 2. Если удалить скомпилированный CSS файл, а потом снова запустить сниппет, то новый файл НЕ будет создан. Он создастся только после любого изменения в SCSS.
> 3. После компиляции у меня вот такое получилось в CSS (переменные не "распарсились"):
> 
> ```css
> :root{--font-family: $font-family;--ui-font-family: $ui-font-family}
> ```
> 
> 4. Ошибка в журнале при компиляции (насколько понял только при первом создании CSS):
> 
> ```
> ...30.include.cache.php : 95) PHP warning: mkdir(): File exists
> ...30.include.cache.php : 95) SCSS - Не удалось создать директорию: Z:/home/modx.local/3//assets/styles
> ```

Спасибо, что указали на мои ошибки.
Как будет время исправлю.
